In [1]:
import sys
import numpy as np  # Fundamentwl package for scientific community. "numpy" stands for numerical python

# Numpy

#### Numpy Documentation : https://numpy.org/

In [2]:
# Numpy provides datatypes such as one-dimentional array,multidimentional arrays
# List can be treated as arrays, matrix(List of Lists)
# numpy arrays are more fast than List data type in python. Since, numpy uses fixed data type.
# Numpy interger is by default int32
# List - Object Value, Object Type, Reference Count, Size. 
# Numpy utilizes contiguous memory
# Since, List use reference to store values , memory blocks are scattered and not contiguous
# SIMD Vector Processing -  Single Instruction Multiple Data.
# Effective cache utilization by numpy
# numpy applications - Mathematics, Backend(pandas,Connect 4,Digital Photography), Machine Learning Applications.
# Tensor library is similar to numpy library.
# Scipy is more mathematics driven

In [3]:
# Can not multipl lists.
a = [1,2,3]
b = [2,3,4]
# a*b   <- This will produce error

# Can multiply numpy arrays.
a = np.array([1,2,3])
b=np.array([2,3,4])
a*b

array([ 2,  6, 12])

In [4]:
# Defining arrays
a = np.array([1,2,3,4],dtype='int8')
print(a)
print(a.ndim)
print(a.ndim)
print('size(no of elements): {}'.format(a.size))
print('*******')
b=np.array([2.4,5.9,8.7])
print(b)
print(type(a))

[1 2 3 4]
1
1
size(no of elements): 4
*******
[2.4 5.9 8.7]
<class 'numpy.ndarray'>


In [5]:
f=np.array([1,2,3,4,5])
f[[1,2,4]]

array([2, 3, 5])

In [6]:
a=np.array([[2.4,5.9,8.7],[3.6,4.6,5.4]])
print(a)
#get dimention
print(a.ndim)
print(a.shape)
print(a.size)  # Number of elements
print(a.itemsize)
print(a.nbytes)
print('*******')

b=np.array([[2.4,5.9,8.7],[3,4,5]])
print(b)

[[2.4 5.9 8.7]
 [3.6 4.6 5.4]]
2
(2, 3)
6
8
48
*******
[[2.4 5.9 8.7]
 [3.  4.  5. ]]


In [7]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

# If number of elements do not match then it creates a list of list

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [8]:
# Get specific Elelemt [r,c]
print(a[1,5])
print(a[1,-2])

13
13


In [9]:
# get specific row
a[0,:] # basic slice syntax

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [11]:
a[:,2][0]

3

In [12]:
# [startindex:endindex:stepsize] endindex is exclusive
a[0,1:6:2]

array([2, 4, 6])

In [13]:
a[1,5]=20
print(a)
a[1,5]=13 
print(a[1,5])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
13


In [14]:
a[:,2]=900
print(a)

a[:,2]=[3,10]
print(a)

[[  1   2 900   4   5   6   7]
 [  8   9 900  11  12  13  14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


-> 3-d example :

In [15]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
# Get specific element (Work outside in)
d[0,1,1]

4

In [17]:
print(d[0,:,1])
print("--------")
print("--------")
print(d[:,0,:])
print(d[:,0,:][1])
print(d[:,0,:][1][0])

[2 4]
--------
--------
[[1 2]
 [5 6]]
[5 6]
5


In [18]:
# Initilizing different types of array : 
# np.zeros, np.ones,np.full,np.full_like,np.random.rand,np.random.random_sample,np.random.randint, np.identity,np.repeat

a=np.zeros(5)
print(a)
print("1-----")
a=np.zeros((2,3))
print(a)
print("2-----")
a= np.zeros((2,2,2))
print(a)
print("3-----")

a=np.ones(1,dtype='int16')
print(a)
print("4-----")
a=np.full((2,2),99,dtype='float32')
print(a)

print("5-----")
a=np.random.rand(4,2)
print(a)
print("6-----")
a=np.identity(3,dtype='int16')
print(a)
print("7-----")


[0. 0. 0. 0. 0.]
1-----
[[0. 0. 0.]
 [0. 0. 0.]]
2-----
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
3-----
[1]
4-----
[[99. 99.]
 [99. 99.]]
5-----
[[0.97125113 0.86544909]
 [0.83824259 0.72175208]
 [0.99719268 0.31404062]
 [0.32983245 0.02459959]]
6-----
[[1 0 0]
 [0 1 0]
 [0 0 1]]
7-----


In [19]:
# Repeat an array
arr= np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [20]:
a=np.array([1,2,3])
b=a # this only creates the reference
b[0]=100
print(b)
print(a)
print("******")
a[0]=1
b=a.copy()    #a.copy copies the data into the newly defined array
b[0]=100
print(b)
print(a)

[100   2   3]
[100   2   3]
******
[100   2   3]
[1 2 3]


#### Arange

In [21]:
a=np.arange(1,10)
print(a)
a=np.arange(3)
print(a)
a=np.arange(1,10,2)
print(a)
a=np.arange(10,dtype='complex')
print(a)
a=np.arange(10,dtype='float32')
print(a)

[1 2 3 4 5 6 7 8 9]
[0 1 2]
[1 3 5 7 9]
[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### linspace

In [22]:
a=np.linspace(1,100,num=5)
print(a)

a=np.linspace(1,100,num=5,endpoint=False)
print(a)


[  1.    25.75  50.5   75.25 100.  ]
[ 1.  20.8 40.6 60.4 80.2]


### Mathematical Functions :

In [23]:
a=np.array([1,2,3,4])
b=np.array([2,4,5,5])

print(a+2)
print(a-2)
print(a*0)
print(a**2)
print(np.sin(a))

print(a+b)
print(a*b)
print(a/b)

print(a)

[3 4 5 6]
[-1  0  1  2]
[0 0 0 0]
[ 1  4  9 16]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[3 6 8 9]
[ 2  8 15 20]
[0.5 0.5 0.6 0.8]
[1 2 3 4]


#### Linear Algebra

In [24]:
# Matrix Multiplication

a = np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)



# print(a*b) -> This will not work.

np.matmul(a,b) 

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [25]:
# Determinant of a matrix
# Other operations : inverse,matrix norm,singular vector decomposition,trace,eigen values,eigen vector etc.

a = np.identity(3)
print(a)
np.linalg.det(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

#### Solving Linear Equation :

In [26]:
# Equation 1 : 3x + y = 9
# Equation 2 : x + 2y = 8
# Equations are represented as below
eq1 = np.array([[3,1],[1,2]])
eq2 = np.array([9,8])
np.linalg.solve(eq1,eq2)
# This gives out x and y values


# Similarly, np.linalg.solve() can be used to solve higher order polynomial equations by representing equations using np arrays

array([2., 3.])

#### Statistics in Numpy :

In [27]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
print(np.min(stats),np.max(stats),np.mean(stats))
print(np.min(stats,axis=1))
print(np.max(stats,axis=1))

1 6 3.5
[1 4]
[3 6]


##### Reorganizing arrays

In [29]:
# Reshaping
before=np.array([1,2,3,4])
after=before.reshape((2,2))
print(after)
after=before.reshape((4,1))
print(after)
print("**************")

# Vertical Stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])


# Horizontal Stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.hstack([v1,v2])

[[1 2]
 [3 4]]
[[1]
 [2]
 [3]
 [4]]
**************


array([1, 2, 3, 4, 5, 6, 7, 8])

#### Miscellaneous
- Load data from file (np.genfromtxt)

In [30]:
filedata=np.genfromtxt('data.txt',delimiter=',')
# filedata=np.genfromtxt('data.txt',delimiter=',',dtype='int32') This will also work
filedata=filedata.astype('int32')
print(type(filedata))
filedata


<class 'numpy.ndarray'>


array([[  1,   2,   3],
       [ 12,  34,  56],
       [123, 456, 789]])

##### Boolean masking and Advance Indexing

In [31]:
filedata > 50

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [32]:
filedatanew=filedata[filedata>50]
filedatanew

array([ 56, 123, 456, 789])

In [33]:
print(np.any(filedata>50,axis=0))   # Column wise
print(np.all(filedata>50,axis=0))   # All values in a column

[ True  True  True]
[False False False]


In [34]:
~(filedata > 50)

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [35]:
data=np.array(range(1,31))
data


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [36]:
data=data.reshape((6,5))
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [37]:
print(data[2:4,0:2])
print("******")

print(data[[0,1,2,3],[1,2,3,4]])

print("******")

print(data[[0,4,5],3:])

[[11 12]
 [16 17]]
******
[ 2  8 14 20]
******
[[ 4  5]
 [24 25]
 [29 30]]


# ===========================Scipy============================

#### Scipy Documentation : https://www.scipy.org/scipylib/index.html

In [38]:
# it is based on numpy extension
# built on ATLAS LAPACK and BLAS
# is used to solve mathematical and scientific problems
# cluster, constant, integrate, interpolate, linalg, ndimage, signal, sparse, stats, fftpack, io, special

In [39]:
from scipy import cluster

In [40]:
#help()
#scipy.help(cluster)
#scipy.info(cluster)
#scipy.source(cluster)

#### Special  :

In [41]:
from scipy import special

In [42]:
a = special.exp10(3)
b = special.exp2(3)
a,b

(1000.0, 8.0)

In [43]:
c = special.sindg(90)
d = special.cosdg(90)
c,d

(1.0, -0.0)

#### Integration :

In [44]:
from scipy import integrate
# help(integrate.quad)
# quad, dblquad

In [45]:
i = integrate.quad(lambda x : special.exp10(x),0,1)
i

(3.9086503371292665, 4.3394735994897923e-14)

In [46]:
e = lambda x,y: x * (y**2)
f = lambda x: 1
g = lambda x: -1

integrate.dblquad(e,0,5,f,g)  # Double integral

(-0.0, 2.7532141922311115e-13)

#### Fourier

In [47]:
# Fourier transformation is expressing function as a sum of periodic components
from scipy.fftpack import fft,ifft

In [48]:
x=np.array([1,2,3,4])
y=fft(x)   # y = ifft(x)
y

array([10.-0.j, -2.+2.j, -2.-0.j, -2.-2.j])

#### Linear Algebdra

In [49]:
from scipy import linalg

a = np.array([[1,2],[3,4]])
b=linalg.inv(a)
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

#### Interpolation

In [50]:
# Interpolation refers to constructing new data points within a set of known data points
# scipy.interpolate
# one-dimentional and multi-dimentional(univariate and multivariate) interpolation classes

In [51]:
import matplotlib.pyplot as plt
from scipy import interpolate

x=np.arange(5,20)
y=np.exp(x/3.0)
f=interpolate.interp1d(x,y)
x1=np.arange(6,12)
y1=f(x1)
plt.plot(x,y,'o',x1,y1,'--')
plt.show()

<Figure size 640x480 with 1 Axes>